# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CLI CI

on:
  push:
    branches: [ task-2-CLI-grep ]
  pull_request:
    branches: [ task-2-CLI-grep ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Go to project directory
      run: cd CLI
    - name: Grant execute permission for gradlew
      run: pwd
    - name: Build with Gradle
      run: ./gradlew test
